### ISSUE TITLE
Merge PREvant's IngressRoute Into Services' IngressRoutes

### ISSUE THREAD

**Issue by schrieveslaach** [aixigo/PREvant#108]
If PREvant is combined with [Let's Encrypt ACME Resolver](https://doc.traefik.io/traefik/user-guides/crd-acme/) and [Traefik Forward Auth](https://github.com/thomseddon/traefik-forward-auth), the [Traefik's custom IngressRoute](https://doc.traefik.io/traefik/providers/kubernetes-crd/) would look like the following:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: kube-system
  name: prevant-ingress-route
spec:
   # Let's encryprt
   # -------- ACME begin --------
   entryPoints:
    - https
   tls:
      certResolver: myresolver
   # -------- ACME end --------
   routes:
    - kind: Rule
      # Host is required for ACME
      match: PathPrefix(`/`) && Host(`prevant.example.com`)
      priority: -100
      services:
       - name: prevant
         port: 80
      # Middleware is required for Traefik Forward Auth
      middlewares:
       - name: traefik-forward-auth
```

If services are then deployed through PREvant, their IngressRoutes look like this:

```yaml
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      com.aixigo.preview.servant.app-name: master
      com.aixigo.preview.servant.container-type: instance
      com.aixigo.preview.servant.service-name: whoami
      traefik.ingress.kubernetes.io/router.entrypoints: web
    creationTimestamp: "2022-09-21T09:47:35Z"
    generation: 1
    name: master-whoami-ingress-route
    namespace: master
  spec:
    routes:
    - kind: Rule
      match: PathPrefix(`/master/whoami/`)
      middlewares:
      - name: master-whoami-middleware
      services:
      - kind: Service
        name: whoami
        port: 80
```

However, that makes the service unreachable and it would be necessary to have following IngressRoute for the service:

```yaml
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      com.aixigo.preview.servant.app-name: master
      com.aixigo.preview.servant.container-type: instance
      com.aixigo.preview.servant.service-name: whoami
      traefik.ingress.kubernetes.io/router.entrypoints: web
    creationTimestamp: "2022-09-21T09:47:35Z"
    generation: 1
    name: master-whoami-ingress-route
    namespace: master
  spec:
    entryPoints:
      - https
    tls:
      certResolver: myresolver
    routes:
    - kind: Rule
      match: PathPrefix(`/master/whoami/`)  && Host(`prevant.example.com`)
      middlewares:
      - name: traefik-forward-auth
      - name: master-whoami-middleware
      services:
      - kind: Service
        name: whoami
        port: 80
```

Some further considerations:

- `PathPrefix` should be merged so that PREvant under a URL should be available as well (that could make running integration tests in parallel)
- `priority: -100` won't be necessary anymore if the merged IngressRoute receives a higher priority as well.

**Comment by schrieveslaach** [comment]
Implementation hints:

- Use the [`downwardAPI`](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) to mount pod information [into a volume](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) so that PREvant is able to query for its Service and IngressRoute.
```yaml
            volumeMounts:
               - mountPath: /run/podinfo
                 name: podinfo
         volumes:
          - name: podinfo
            downwardAPI:
               items:
                - path: "labels"
                  fieldRef:
                     fieldPath: metadata.labels
```
- Path for the labels should be configurable but the default location is `/run/podinfo/labels`
- Figment could provide alternative so that users could use env vars as well (see https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/)
