### ISSUE TITLE
Support named ports from services

### ISSUE THREAD

**Issue by m007** [aixigo/PREvant#248]
# Issue
We just discovered that an `IngressRoute` is created with `port: 80`
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/xyz/`) && Host(`my-host`)
    middlewares:
    - name: schema-registry-middleware
    services:
    - kind: Service
      name: schema-registry
      port: 80
```
(skipped the metadata) even though the corresponding service is created as 
```yaml
apiVersion: v1
kind: Service
spec:
  clusterIP: 10.43.194.91
  clusterIPs:
  - 10.43.194.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: infra
    app.kubernetes.io/name: schema-registry
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
(skipped metadata again) i.e. `port: 8081`. This does not match. For the `IngressRoute` to work it must match the port of the `Service`.

The original `Ingress` object looked like this
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: schema-registry
  namespace: "xxxxxxx"
  labels:
    app.kubernetes.io/instance: infra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/version: 7.9.0
    helm.sh/chart: schema-registry-25.1.0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: true
spec:
  ingressClassName: "nginx"
  rules:
    - host: schema-registry.local
      http:
        paths:
          - path: /schema-registry
            pathType: ImplementationSpecific
            backend:
              service:
                name: schema-registry
                port:
                  name: http
```

# Proposed solution

Somehow make PREvant automatically use the corresponding `Service` object to define the `port` of the `IngressRoute`.
