### ISSUE TITLE
Hooks for Advanced Skripting

### ISSUE THREAD

**Issue by schrieveslaach** [aixigo/PREvant#41]
This issue is currently just an idea. 

Users of PREvant want to extend configurations of services dynamically. This custom configuration might be based on some team-specific development processes and potentially on some state that needs to be persisted. 

Therefore, PREvant could make use of the scripting engine [rhai](https://github.com/jonathandturner/rhai):

In the configuration PREvant could offer a hooks section:

```toml
[hooks.preDeployment]
script = '/path/to/preDeployment.rhai'
stateful = true

[hooks.postDeletion]
script = '/path/to/postDeletion.rhai'
stateful = true
```

Based on this example PREvant would execute `/path/to/preDeployment.rhai` with app name, service configurations, state, etc. and the script could modify, fitler, the service configurtions and state, before the actual deployment happens.

This could replace the secrets eventually.
